<?xml version="1.0" encoding="UTF-8"?>
<robot name="car" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 包含其他xacro文件 -->
    <xacro:include filename="$(find track)/urdf/common.xacro" />
    
    <!-- Robot type parameter -->
    <xacro:arg name="robot_type" default="track_car"/>
    
    <!-- Materials -->
    <material name="yellow">
        <color rgba="1 1 0 1"/>
    </material>
    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- Add virtual root link -->
    <link name="virtual_root"/>
    
    <joint name="virtual_joint" type="fixed">
        <parent link="virtual_root"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Base parameters -->
    <xacro:property name="base_radius" value="0.20"/>
    <xacro:property name="base_length" value="0.30"/>
    <xacro:property name="base_height" value="0.15"/>
    
    <!-- Wheel parameters -->
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_ygap" value="0.20"/>
    <xacro:property name="wheel_zoff" value="0.05"/>
    <xacro:property name="wheel_xoff" value="0.12"/>

    <!-- Main body link -->
    <link name="base_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.0395" ixy="0" ixz="0" iyy="0.086" iyz="0" izz="0.0125"/>
        </inertial>
        <visual>
            <geometry>
                <box size="${base_length} ${base_radius*2} ${base_height}"/>
            </geometry>
            <material name="yellow" if="$(eval robot_type == 'track_car')"/>
            <material name="green" if="$(eval robot_type == 'target_car')"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_radius*2} ${base_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- 四个车轮宏定义 -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${wheel_xoff * x_reflect} ${wheel_ygap/2 * y_reflect} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>
    </xacro:macro>

    <!-- 添加四个车轮 -->
    <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1" />
    <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1" />
    <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1" />
    <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1" />

    <!-- Camera link and joint -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.05 0.05 0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="0.2 0 0.1" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo plugins -->
    <gazebo reference="camera_link">
        <sensor type="camera" name="camera">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>track_car/camera</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <!-- 修改差速驱动插件配置 -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <leftJoint>front_left_wheel_joint</leftJoint>
            <rightJoint>front_right_wheel_joint</rightJoint>
            <robotNamespace>$(arg robot_type)</robotNamespace>
            <wheelSeparation>0.3</wheelSeparation>
            <wheelDiameter>0.12</wheelDiameter>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>
            <publishWheelTF>false</publishWheelTF>
            <publishOdomTF>true</publishOdomTF>
            <publishWheelJointState>false</publishWheelJointState>
            <wheelAcceleration>1.0</wheelAcceleration>
            <wheelTorque>20</wheelTorque>
            <odometrySource>world</odometrySource>
            <updateRate>30</updateRate>
        </plugin>
    </gazebo>
</robot>
